### PR TITLE
update ERROR_DISPATCH to dispatch_error

### PR DESCRIPTION
**Pull request by samsonasik**
in favor of https://github.com/pennyphp/penny/pull/101

### CODE REVIEW

**Comment by samsonasik** [comment]
as this classic-app uses penny:dev-master, and https://github.com/pennyphp/penny/pull/101 merged, it need to be merged now

**Comment by gianarb** [comment]
Little waring @samsonasik thanks for your merge but this PR is red because the composer.lock did not updated.. This app require dev-master but it is an application and is a good practice push the composer.lock and it fix project at a specific commit of pennyphp :)

**Comment by samsonasik** [comment]
will fix in a few ;)

**Comment by samsonasik** [comment]
should be fixed in https://github.com/pennyphp/penny-classic-app/commit/e850c8343fbb46f5d47473f22c1c3f4f0580e68b

**Comment by samsonasik** [comment]
seems still failed, i'm re-install locally now to get regenerated composer.lock

**Comment by samsonasik** [comment]
latest error build is related with unit tests that seems need to be updated.

**Comment by samsonasik** [comment]
the unit test error:

``` shell
1) AppTest\AppTest::testDispatcherErrorCallsListenerIndex

No calls have been made that match:

  Double\App\EventListener\DispatcherExceptionListener\P1->onError(*)

but expected at least one.
```

**Comment by gianarb** [comment]
The problem is php-di/invoker 1.2.0.. With 1.1.1 works.. :) Now I try to resolve it

**Comment by samsonasik** [comment]
Thanks ;)

Warm regards,

Abdul Malik Ikhsan

Pada 30 Okt 2015, pukul 16.28, Gianluca Arbezzano notifications@github.com menulis:

**Pull request merged**
