### PR TITLE
Updating the development environment to PHP 7.0.3

### PR DESCRIPTION
**Pull request by fntlnz**
Updated the development environment to PHP 7.0.3

Removed the Z-Ray extension, it was useful but too much for a skeleton application.

### CODE REVIEW

**Comment by gianarb** [comment]
:+1: Thanks! I see you by IRC xD

**Comment by fntlnz** [comment]
Damn I have to take the habit to log in IRC :D

**Comment by samsonasik** [comment]
merge-able?

**Comment by fntlnz** [comment]
@samsonasik seems ok to me

**Pull request merged**
